"use client";

import Image from "next/image";
import { ArrowUpRight, Camera, MapPin, CalendarDays, Soup } from "lucide-react";
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { memories, type DiscoverEgg } from "@/lib/birthday";
import { Reveal, SectionHeading } from "./primitives";

export function MemoryScroll({ discover }: { discover: DiscoverEgg }) {
  return <section id="memories" className="memory-section section-space page-width"><div className="section-topline"><SectionHeading number="03" eyebrow="LITTLE MOMENTS. PERMANENT SAVE." title="The memory" emphasis="scroll." description="Because the best moments deserve more than getting lost in the camera roll." /><button className="ramen-egg" aria-label="Take a ramen break" onClick={() => discover("ramen")}><Soup /><span>FOR THE<br />GOOD TIMES</span></button></div><div className="memory-grid">{memories.map((memory, i) => <Reveal key={memory.id} delay={i * 0.08}><Dialog><DialogTrigger className="memory-card" aria-label={`Open memory: ${memory.title}`}><div className="memory-image"><Image src={memory.image} alt={memory.alt} fill sizes="(max-width: 640px) 90vw, 30vw" /><span className="memory-count">0{memory.id} / MEMORY SCROLL</span><span className="memory-open"><ArrowUpRight size={20} /></span>{memory.placeholder && <span className="memory-placeholder"><Camera size={12} /> YOUR PHOTO GOES HERE</span>}</div><div className="memory-caption"><h3>{memory.title}</h3><p>{memory.caption}</p></div></DialogTrigger><DialogContent className="memory-modal"><Image src={memory.image} alt={memory.alt} width={1200} height={900} sizes="(max-width: 768px) 95vw, 800px" className="memory-full-image" /><DialogHeader><DialogTitle>{memory.title}</DialogTitle><DialogDescription>{memory.caption}</DialogDescription></DialogHeader>{(memory.date || memory.location) && <div className="memory-metadata">{memory.date && <span><CalendarDays size={14} />{memory.date}</span>}{memory.location && <span><MapPin size={14} />{memory.location}</span>}</div>}{memory.placeholder && <p className="memory-disclaimer">Illustrated scene, not a personal memory. This space is waiting for your own photo and story.</p>}</DialogContent></Dialog></Reveal>)}</div><p className="memory-footnote"><Camera size={13} />Classic scenes from the Hidden Leaf. Certified shinobi-approved memories.</p></section>;
}
